# Generated by Django 3.2.9 on 2022-10-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0004_product_product_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
