# Generated by Django 3.2.9 on 2022-11-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0005_product_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_number', models.CharField(default='', max_length=10)),
                ('user_email', models.CharField(default='', max_length=200)),
                ('user_address1', models.CharField(default='', max_length=1000)),
                ('user_address2', models.CharField(default='', max_length=1000)),
                ('order_price', models.IntegerField()),
                ('order_date', models.DateField()),
            ],
        ),
    ]
