# Generated by Django 3.2.9 on 2022-11-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_product',
            field=models.JSONField(default='', max_length=1000),
        ),
    ]
