# Generated by Django 3.2.9 on 2022-11-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0007_order_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_product',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
