# Generated by Django 3.2.9 on 2022-11-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0008_alter_order_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='', max_length=50)),
                ('order_status', models.CharField(default='', max_length=100)),
                ('order_desc', models.CharField(default='', max_length=500)),
                ('update_time', models.TimeField()),
            ],
        ),
    ]
